### ISSUE TITLE
[DOCS] Testes end-to-end e Cypress

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#130]

**Comment by FelipeDuarteLuna** [comment]
Iniciamos a Documentação sobre o Teste E2E Cypress: https://github.com/techexpertspro/portal-ascepa/wiki/Cypress-%E2%80%90-Teste-E2E-(End%E2%80%90to%E2%80%90End)
![image](https://github.com/user-attachments/assets/6fb93d0f-9a15-47b5-9fd5-6fbf3cfaed39)

![image](https://github.com/user-attachments/assets/2ab1eba1-0839-40c2-9b58-28ef551ede4e)

**Comment by FelipeDuarteLuna** [comment]
@andrewarosario  e neste cenário da ISSUE que é criação de Documentação do Cypress na WIKI. Como é feito o Pull Request ? ou Apenas encerra este ISSUE ?

**Comment by FelipeDuarteLuna** [comment]
@paoloalmeida  tio da documentação, vê se tem algo a corrigir ou melhorar. Por favor...

**Comment by andrewarosario** [comment]
> @andrewarosario e neste cenário da ISSUE que é criação de Documentação do Cypress na WIKI. Como é feito o Pull Request ? ou Apenas encerra este ISSUE ?

Como é somente Wiki, é só encerrar a Issue mesmo 😉
