### ISSUE TITLE
[DOCS] Criar o guia de como contribuir com o projeto ( CONTRIBUTING.md )

### ISSUE THREAD

**Issue by WilliamDutra** [techexpertspro/portal-ascepa#131]
Notei que ao tentar visualizar o guia de **_"como contribuir com o projeto"_** ele ainda não existe. Apesar do projeto ter uma wiki, seria interessante ter esse guia rápido desde:

- [ ] Como clonar o projeto.
- [ ] Como efetuar um `pull request`.
- [ ] Descrever o que foi feito nesse `pull request`.
- [ ] Como os `commits` são feitos

**Comment by andrewarosario** [comment]
Fala @WilliamDutra! Na verdade o arquivo `CONTRIBUTING.md` já existe, mas o README está apontando para o caminho errado. O caminho correto seria [este aqui](https://github.com/techexpertspro/portal-ascepa/blob/main/docs/CONTRIBUTING.md).

Você poderia subir essa correção? E se quiser enriquecer o guia de contribuição fique a vontade também 😉 
Outro errinho que encontrei também é que na sessão COnecte-se conosco no README, o link do Tech Experts está errado (está https://techesxperts.pro/ e deveria ser https://techexperts.pro/)

Só subir a Pull Request e vincular a Issue. Vou colocar ela no board

**Comment by WilliamDutra** [comment]
Beleza, crie lá o [`pull request`](https://github.com/techexpertspro/portal-ascepa/pull/135) através da [branch](https://github.com/techexpertspro/portal-ascepa/tree/fix/task-131?tab=readme-ov-file)
