### ISSUE TITLE
[SEO] Adicionar Meta Tags para as Pages

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#144]
Meta tags são tags HTML que fornecem metadados sobre uma página da web. Elas são invisíveis para os usuários, mas podem ser usadas por mecanismos de busca e plataformas de mídia social para entender e exibir informações sobre uma página da web.

O Angular fornece uma Service Meta do pacote [@angular/platform-browser](http://twitter.com/angular/platform-browser) que permite manipular meta tags em seu aplicativo Angular.

### DOR
- [ ] Adicionar Meta Tags apropriadas para as páginas internas e home page

### Links úteis
- https://developer.chrome.com/docs/lighthouse/seo/meta-description/
- https://angular.dev/api/platform-browser/Meta
- https://medium.com/@shravanvishwakarma5/meta-tags-in-angular-c483c3e6f0d4

### Estrutura básica para SEO, que pode ser utilizada

```
<meta charset="utf-8">
<meta name="language" content="">
<title></title>
<meta name="description" content="">
<meta name="robots" content="">
<meta name="author" content="">
<meta name="keywords" content="">
<meta property="og:type" content="page">
<meta property="og:url" content="">
<meta property="og:title" content="">
<meta property="og:image" content="">
<meta property="og:description" content="">
<meta property="article:author" content="">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@">
<meta name="twitter:title" content="">
<meta name="twitter:creator" content="@">
<meta name="twitter:description" content="">
```

**Comment by FelipeDuarteLuna** [comment]
Implementação realizada com sucesso. 
Feat/[SEO] Adicionar Meta Tags para as Pages (https://github.com/techexpertspro/portal-ascepa/pull/171)
https://github.com/techexpertspro/portal-ascepa/commit/a804b227698e7e189ce798023534eaeff25fd4fb
