### ISSUE TITLE
[SEO + a11y] Alterar título das páginas

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#149]
Hoje o título principal da página está como `portal-ascepa`. Deve-se trocar para um nome mais descritivo.

**Comment by FelipeDuarteLuna** [comment]
Boa Noite Mestre @andrewarosario , Tudo bom ?

Essa implementação já foi realizada pelo @RenanBotelho , subiu no PR:
https://github.com/techexpertspro/portal-ascepa/pull/160
https://github.com/techexpertspro/portal-ascepa/pull/168

Posso fechar, essa ISSUE ?

**Comment by FelipeDuarteLuna** [comment]
Issue Fechada, devido já ter cido implementado anteriormente pelo @RenanBotelho.
