### ISSUE TITLE
Criar política de segurança

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#28]
Criar diretrizes para informar como as pessoas devem contribuir com o projeto.
https://docs.github.com/pt/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by Flamilani** [comment]
@andrewarosario 

Dei olhada na documentação de github como criar política de segurança, e achei link de política de segurança pra seguir instruções e adicionar um arquivo SECURITY.md: https://docs.github.com/pt/code-security/getting-started/adding-a-security-policy-to-your-repository

No aguardo para verificar essa configuração

**Comment by andrewarosario** [comment]
@Flamilani É exatamente isso! 😉

**Comment by FelipeDuarteLuna** [comment]
Bom dia Time, 

Analisando o projeto, podemos centralizar todos os doc's criando um diretorio docs/guide. Exemplo:

https://github.com/po-ui/po-angular/tree/master/docs/guides

**Comment by andrewarosario** [comment]
> Bom dia Time,
> 
> Analisando o projeto, podemos centralizar todos os doc's criando um diretorio docs/guide. Exemplo:
> 
> https://github.com/po-ui/po-angular/tree/master/docs/guides
> 
> ![image](https://private-user-images.githubusercontent.com/29357935/338538431-b1036c64-edec-451e-83f6-62610d786893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTMxNjAsIm5iZiI6MTcxODExMjg2MCwicGF0aCI6Ii8yOTM1NzkzNS8zMzg1Mzg0MzEtYjEwMzZjNjQtZWRlYy00NTFlLTgzZjYtNjI2MTBkNzg2ODkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzMzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDgxOWEyNjA3ZTBmMjMwNDYxYmVmYmU1ZjgwOTY2ZThjYWEzOTFhY2IxNDRjNjRlOWMwMjQzMjM3OTI0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PFID_C4PK4NZsGzRyvPHWpeYe0wyyG9B8JlLpxP0rGY)
> 
> Outro ponto analisando, podemos adicionar os files CODE_OF_CONDUCT.md e CONTRIBUTING.md na pasta docs/guides/ para centralizar nossa documentação no projeto. O que acham ?

Achei excelente @FelipeDuarteLuna! Assim fica melhor pra centralizar tudo relacionado a documentação
