### ISSUE TITLE
Integrar o SonarCloud

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#43]
### Discussed in https://github.com/techexpertspro/portal-ascepa/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **andrewarosario** June  7, 2024</sup>
O SonarCloud é uma plataforma de análise de qualidade de código e segurança fornecida como um serviço (SaaS). Ele ajuda desenvolvedores e equipes a melhorar a qualidade do código e a detectar vulnerabilidades em tempo real, integrando-se facilmente com vários serviços de hospedagem de código, como o GitHub.

É possível integrar o o SonarCloud com um repositório GitHub de forma gratuita. O SonarCloud oferece um plano gratuito para projetos open-source.</div>

- Criação do projeto `portal-ascepa` no SonarCloud: https://sonarcloud.io/project/overview?id=portal-ascepa
O projeto está vinculado a nossa organization, portanto ao logar no SonarCloud, utilize o Github

- Integração da análise do Sonar pelo Github Actions

**Comment by FelipeDuarteLuna** [comment]
Bom dia @andrewarosario você já fez esse trampo ? Posso fazer ?

**Comment by andrewarosario** [comment]
Bom dia @FelipeDuarteLuna, eu tinha iniciado mas pausei ele por conta de precisar fazer algumas configurações pra pegar o coverage certinho. Mas pode pegar sim.
