### ISSUE TITLE
Integrar Commitlint

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#47]

**Comment by andrewarosario** [comment]
O @LuccasTraumer já subiu a implementação em uma outra PR #44 . 
Depois que subir a PR #22 acho que já podemos voltar com essa PR dele

**Comment by FelipeDuarteLuna** [comment]
Bom dia Time, acabei assumindo a issue... vê que estava em branco. Quer tocar @LuccasTraumer ?

**Comment by andrewarosario** [comment]
Opa, como o @LuccasTraumer já tinha subido a PR #44 acho que seria bacana ele tocar essa

**Comment by LuccasTraumer** [comment]
PR foi feito, necessario code review apenas para fechamento da Issuo
