### ISSUE TITLE
Criar layout module

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#55]
Para termos uma melhor separação de responsabilidades e uma melhor performance no CI/CD, precisamos criar um módulo do `layout` da aplicação. 
Este módulo terá os componentes que serão renderizados em todas as páginas do portal, como o **Header** e o **Footer**.

Executar Generator de criação de módulos do projeto:
```bash
npx nx generate @portal-ascepa/angular-plugin:module --name=layout
```

### Definition of done
- [x] Executar generator do Nx
- [x] Adicionar uma breve descrição no arquivo `README.md` do módulo que será gerado (Documentação nunca é demais 😆 )

**Comment by Flamilani** [comment]
Gostaria de saber que estão aprimorando README.md até finalizar, depois atuar esta tarefa pra gerar módulo layout e colocar descrição no arquivo mesmo no README.md?

**Comment by andrewarosario** [comment]
@Flamilani Muito bem pontuado. Esqueci de comentar: cada módulo gerado com o Nx terá seu próprio `README.md`. O ideal é alterar somente o README do próprio módulo gerado. O README principal não deve ser alterado.
