### ISSUE TITLE
Ajustes de readme de política de segurança e MIT license por formatação e idioma inglês

### ISSUE THREAD

**Issue by Flamilani** [techexpertspro/portal-ascepa#67]
## Descrição
Tinha reparado que há a diferença de formatação entre MIT License (como está fora de formatação) e outros que estão bem formatado

## Comportamento esperado
Seria legal padronizar a formatação e o idioma. Como são arquivos abertos fica melhor deixar tudo em inglês.

## Exemplos

Idioma de português
![Captura de tela 2024-06-14 215335](https://github.com/techexpertspro/portal-ascepa/assets/6421882/83e8aa57-aa4a-49aa-b9f6-a83633e7be06)

Idioma de inglês
![Captura de tela 2024-06-14 215648](https://github.com/techexpertspro/portal-ascepa/assets/6421882/63efdeaf-8491-47c0-9afa-3cfd8effd188)

Fora de formatação:
![Captura de tela 2024-06-14 215408](https://github.com/techexpertspro/portal-ascepa/assets/6421882/84c8051b-3d50-4239-81f3-07f4016bfe2f)

**Comment by Flamilani** [comment]
@charlesribeiro ótimo, claro que a gente pode trabalhar juntos
tem docs para ajustar:
CONTRIBUITING.md e SECURITY.md para converter para inglês

a gente divide esses docs

**Comment by Flamilani** [comment]
@charlesribeiro segue branch criada para utilizar localmente: docs/formatting-language-docs-md

**Comment by charlesribeiro** [comment]
@Flamilani ótimo, não encontrei essa branch com esse nome

docs/formatting-language-docs-md

por isso, criei ela em origin e adicionei meu commit

caso, queira, mudarei para a branch onde você está trabalhando atualmente

**Comment by Flamilani** [comment]
Opa. Ah sem problemas. Pode separar outra branch com arquivo separado pois
vi que já abriu PR pra revisar

Em ter., 18 de jun. de 2024, 19:56, charlesribeiro ***@***.***>
escreveu:

**Comment by Flamilani** [comment]
@charlesribeiro deu certo que baixei sua alteração no arquivo SECURITY.md que foi traduzido pra inglês e acabei de subir minhas alterações na mesma branch, mas deu erro de lint no actions, depois vou verificar isso.

**Comment by Flamilani** [comment]
@charlesribeiro agora está tudo certo nas esteiras que passaram, podemos mover pra code review
