### ISSUE TITLE
[IMPROVEMENT] Ícone do portal ASCEPA

### ISSUE THREAD

**Issue by charlesribeiro** [techexpertspro/portal-ascepa#73]
## Descrição

Precisamos de um ícone apropriado (_favicon_) para o website

## Comportamento esperado

Atualmente temos apenas o ícone padrão do NX no nosso portal

## Exemplos
Aba da aplicação deployada

![Screenshot 2024-06-18 at 22 40 59](https://github.com/techexpertspro/portal-ascepa/assets/24253971/b540afc2-0220-4fe3-aae5-b902fc7262be)

## Outras observações

Creio que o ícone vai ser fornecido mais pra frente pelos responsáveis pelo design, mas acho que não custa nada manter essa task no radar.

**Comment by ortegavan** [comment]
Assumi a task, assim que enviarem logo/ícone providencio o .ico e atualizo. ;)

**Comment by ortegavan** [comment]
@andrewarosario @paoloalmeida Como a logo deles tem muitas cores e gradiente, fica complicado usá-la para gerar o .ico. Vocês acham que podemos usar alguma outra imagem? Se sim, têm alguma ideia? Tenho assinatura premium do https://www.flaticon.com caso queiram dar uma pesquisada.

**Comment by andrewarosario** [comment]
@ortegavan eu acho que vale a pena usar uma outra imagem sim. Talvez uma do FlatIcon que mais se assemelha à original.

**Comment by jpsthome** [comment]
Não dá pra pegar a logo deles e fazer um todo branco ou preto?

**Comment by ortegavan** [comment]
@jpsthome se alguém tiver habilidades no Illustrator (eu não tenho) poderia tentar. Mas eu acho que, ainda assim, pela quantidade de detalhes, não ficaria bom pequenininho para favicon. Se alguém quiser tentar fazer no Illustrator, poderia dar uma simplificada, talvez só manter as mãos e os olhos e só com outline.

**Comment by Flamilani** [comment]
Boa tarde pessoal e @ortegavan, eu tenho Illustrator aqui, se puder colaborar para ajustar imagem e favicon, pode contar

**Comment by ortegavan** [comment]
@Flamilani Opa! Acha que conseguiria fazer uma nova versão simplificada da logo em anexo? Talvez só as mãos e os olhos, e só contorno. 

![Image](https://github.com/techexpertspro/portal-ascepa/assets/30645960/3b96bc8f-20e2-4972-81a9-d6bf0957e016)

**Comment by Flamilani** [comment]
@ortegavan Boa, sim pode deixar que vou fazer nova versão da logo com contorno de mãos e olhos, depois mandarei para ver como ficaria.

**Comment by Flamilani** [comment]
Boa noite, @ortegavan, segue as imagens de contorno da logo, qualquer coisa precisa de alguns ajustes, pode avisar
![contorno-ascepa-1](https://github.com/techexpertspro/portal-ascepa/assets/6421882/0257a66c-a5cf-42e4-b15d-3a8fdd313c36)
![contorno-ascepa-2](https://github.com/techexpertspro/portal-ascepa/assets/6421882/58a0484b-9b44-4d01-a77b-7f3a591adfe0)
![contorno-ascepa-3](https://github.com/techexpertspro/portal-ascepa/assets/6421882/3126361e-2534-458e-9747-589d34cd0b94)

**Comment by ortegavan** [comment]
Eu curti! Mas será que pra favicon fica bom? O que acham @andrewarosario e @paoloalmeida ?

**Comment by andrewarosario** [comment]
O favicon amarelo eu achei bem bacana!

**Comment by ortegavan** [comment]
Curti o amarelo também!

**Comment by Flamilani** [comment]
@ortegavan, tentei converter em svg, mas não pega cor amarelo, somente branco e preto.

![Image](https://github.com/techexpertspro/portal-ascepa/assets/6421882/4cdbd8f4-9e30-46be-aa9f-a0f82b54b996)

**Comment by ortegavan** [comment]
Perfect! Peguei aqui.

**Comment by andrewarosario** [comment]
Movendo a Issue para a coluna de **Ready**
