### ISSUE TITLE
[BUG] LICENSE.md deve estar fora de docs

### ISSUE THREAD

**Issue by Flamilani** [techexpertspro/portal-ascepa#76]
## Descrição
LICENSE.md deve estar fora de docs para exibir aba no README.md

**Comment by andrewarosario** [comment]
Muito bem observado @Flamilani! Vinculei no board na coluna de Ready.

**Comment by Flamilani** [comment]
@andrewarosario @ronefalcao coloquei vocês como revisores para aprovar PR
