### ISSUE TITLE
[módulo] Criar lib home

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#88]
Para termos uma melhor separação de responsabilidades e uma melhor performance no CI/CD, precisamos criar um módulo `home` da aplicação. 
Este módulo terá os componentes da home page da aplicação.

Executar Generator de criação de módulos do projeto:
```bash
npx nx generate @portal-ascepa/angular-plugin:module --name=home
```

### DOD
- [x] Lib gerada pelo Generator
- [x] Componente de HomePage (sem nenhuma implementação ainda) 
- [ ] Adicionar uma breve descrição no *novo* arquivo `README.md` que será gerado com a lib

**Comment by ManoelOscar35** [comment]
O módulo home não vai  está dentro da feature não, como tem nas aulas gravadas?

**Comment by andrewarosario** [comment]
Ótimo ponto @ManoelOscar35! Como o Portal não será uma aplicação extremamente grande, pensei em não trabalhar com a separação de camadas, mais para facilitar o desenvolvimento. Mas se acharem interessante, podemos discutir sobre 😉

**Comment by ManoelOscar35** [comment]
A não beleza.

**Comment by Werisu** [comment]
Bom, vou tocar essa task sozinho por enquanto. Blz @andrewarosario @@paoloalmeida ? Parece que de ontem para hoje, ngm foi adicionado nela.

**Comment by andrewarosario** [comment]
@Werisu pode mandar bala!
