### ISSUE TITLE
[DOCS] Criar Wiki sobre Pipeline de CI/CD com Github Actions

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#97]
Criar uma página dentro da nossa [Wiki](https://github.com/techexpertspro/portal-ascepa/wiki) com a documentação sobre o **Pipeline de CI/CD com Github Actions**.

Referências:
#5 

### DOD
- [x] O que é CI/CD
- [x] O que é Github Actions
- [x] Quais benefícios ele proporciona para o projeto
- [x] Como ele está configurado no projeto
- [x] Links e referências

**Comment by brunoredes** [comment]
https://github.com/techexpertspro/portal-ascepa/wiki/Pipelines-CI-CD

**Comment by andrewarosario** [comment]
Excelente! Super completa e muito bem detalhada 👏 👏
