### ISSUE TITLE
[DOCS] Criar Wiki para o Generator de módulos do projeto

### ISSUE THREAD

**Issue by andrewarosario** [techexpertspro/portal-ascepa#99]
Criar uma página dentro da nossa [Wiki](https://github.com/techexpertspro/portal-ascepa/wiki) com a documentação sobre o **Generator de módulos do projeto**.

Referências:
#6 

### DOR
- [x] #98 

### DOD
- [x] Benefícios ao utilizar o generator
- [x] Como utilizar o generator

**Comment by vitorcbs** [comment]
Link para a página da wiki: 
https://github.com/techexpertspro/portal-ascepa/wiki/Generator-de-m%C3%B3dulos-do-projeto

**Comment by andrewarosario** [comment]
> Link para a página da wiki: https://github.com/techexpertspro/portal-ascepa/wiki/Generator-de-m%C3%B3dulos-do-projeto

Ficou excelente, @vitorcbs :rocket:
